services:
  hr-api:
    build: .
    ports:
    - "8000:8000"
    environment:
    - CHROMA_EMBEDDING_MODEL=all-MiniLM-L6-v2
    - RELEVANCE_THRESHOLD=0.65
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
    - hrnet


networks:
  hrnet:
    driver: bridge